<?php require_once('../../Connections/karaoke_db.php'); ?>
<?php
// Load the common classes
require_once('../../includes/common/KT_common.php');

// Load the tNG classes
require_once('../../includes/tng/tNG.inc.php');

// Make a transaction dispatcher instance
$tNGs = new tNG_dispatcher("../../");

if (!function_exists("GetSQLValueString")) {
function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  if (PHP_VERSION < 6) {
    $theValue = get_magic_quotes_gpc() ? stripslashes($theValue) : $theValue;
  }

  $theValue = function_exists("mysql_real_escape_string") ? mysql_real_escape_string($theValue) : mysql_escape_string($theValue);

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? doubleval($theValue) : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}
}

session_start();
$PHPSESSID = session_id();

$colname_rs_onsell = "-1";
if (isset($_GET['productonsell_product_link_id'])) {
  $colname_rs_onsell = $_GET['productonsell_product_link_id'];
}
mysql_select_db($database_karaoke_db, $karaoke_db);
$query_rs_onsell = sprintf("SELECT * FROM v_product_onsell WHERE productonsell_product_link_id = %s", GetSQLValueString($colname_rs_onsell, "int"));
$rs_onsell = mysql_query($query_rs_onsell, $karaoke_db) or die(mysql_error());
$row_rs_onsell = mysql_fetch_assoc($rs_onsell);
$totalRows_rs_onsell = mysql_num_rows($rs_onsell);

// Show Dynamic Thumbnail
$objDynamicThumb1 = new tNG_DynamicThumbnail("../../", "KT_thumbnail1");
$objDynamicThumb1->setFolder("../uploads-admin/");
$objDynamicThumb1->setRenameRule("{rs_onsell.products_filename}");
$objDynamicThumb1->setResize(95, 95, true);
$objDynamicThumb1->setWatermark(false);

// Show Dynamic Thumbnail
$objDynamicThumb2 = new tNG_DynamicThumbnail("../../", "KT_thumbnail2");
$objDynamicThumb2->setFolder("../uploads-admin/");
$objDynamicThumb2->setRenameRule("{rs_onsell.manufacturers_filename}");
$objDynamicThumb2->setResize(35, 25, true);
$objDynamicThumb2->setWatermark(false);
?>
<style type="text/css">
.details_button {
	-moz-box-shadow:inset 0px 1px 0px 0px #caefab;
	-webkit-box-shadow:inset 0px 1px 0px 0px #caefab;
	box-shadow:inset 0px 1px 0px 0px #caefab;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #77d42a), color-stop(1, #5cb811) );
	background:-moz-linear-gradient( center top, #77d42a 5%, #5cb811 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#77d42a', endColorstr='#5cb811');
	background-color:#77d42a;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #268a16;
	display:inline-block;
	color:#306108;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:4px 12px;
	text-decoration:none;
	text-shadow:1px 1px 0px #aade7c;
}.details_button:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #5cb811), color-stop(1, #77d42a) );
	background:-moz-linear-gradient( center top, #5cb811 5%, #77d42a 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#5cb811', endColorstr='#77d42a');
	background-color:#5cb811;
}.details_button:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
<style type="text/css">
.buy_now_button {
	-moz-box-shadow:inset 0px 1px 0px 0px #f29c93;
	-webkit-box-shadow:inset 0px 1px 0px 0px #f29c93;
	box-shadow:inset 0px 1px 0px 0px #f29c93;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #fe1a00), color-stop(1, #ce0100) );
	background:-moz-linear-gradient( center top, #fe1a00 5%, #ce0100 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fe1a00', endColorstr='#ce0100');
	background-color:#fe1a00;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #d83526;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:4px 14px;
	text-decoration:none;
	text-shadow:1px 1px 0px #b23e35;
}.buy_now_button:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ce0100), color-stop(1, #fe1a00) );
	background:-moz-linear-gradient( center top, #ce0100 5%, #fe1a00 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ce0100', endColorstr='#fe1a00');
	background-color:#ce0100;
}.buy_now_button:active {
	position:relative;
	top:1px;
}
.onesell_image a:link {
	border: 0;
}
</style>

<div style="position: relative; border: 1px solid grey; background-color: white; width: 300px; height: 110px; float: left; margin-right: 10px; margin-top: 10px;">
<?
				if ($row_rs_onsell['products_date_modified']< ('-30 days')) {
				?>
				
				<div style="position: absolute; left: -7px; top: -7px; z-index: 100000;" class="onsale_badge"><img src="/images/new_badge.png" /></div>
				<?
				}
				?>
				
<?
				if ($row_rs_onsell['products_isOnSale']=="1") {
				?>
					<div style="position: absolute; right: -7px; top: -7px; z-index: 100000;" class="onsale_badge"><img src="/images/on_sale_badge.png" /></div>
				<?
				}
				?>
	<div style="position: absolute; width: 109px; height: 25px; background-color: rgba(0,0,0,0.7); bottom: 13px; z-index:1000;">
        <div style="margin-left: 28px; margin-top: 3px; color: white">$<?php echo $row_rs_onsell['products_regularPrice']; ?></div>
    </div>
	<div class="onesell_image" style="position: relative; width: 110px; height: 110px; text-align: center; margin: 0 auto; border-right: 1px solid grey; display: table-cell; vertical-align: middle;">
    	
    	
    	
    	
    	<?
		if($row_rs_onsell['subcategories_subcategorygroup_id']) {
			$setSubcategoryGroupsId=$row_rs_onsell['subcategories_subcategorygroup_id'];
		} else {
			$setSubcategoryGroupsId=0;
		}

		if($row_rs_onsell['subcategories_id']) {
			$setSubcategoriesId=$row_rs_onsell['subcategories_id'];
		} else {
			$setSubcategoriesId=0;
		}

		if($row_rs_onsell['subcategories_title']) {
			$setSubcategories_title=$row_rs_onsell['subcategories_title'];
		} else {
			$setSubcategories_title=0;
		}

	?>
		<a href="/product/<?php echo $row_rs_onsell['categories_id']; ?>/<?php echo $setSubcategoryGroupsId; ?>/<?php echo $setSubcategoriesId; ?>/<?php echo $row_rs_onsell['products_id']; ?>/<?php echo $setSubcategories_title; ?>/<?php echo str_replace(' ', '-',$row_rs_onsell['categories_title']); ?>/<?php echo str_replace(' ', '-',$row_rs_onsell['manufacturers_title']); ?>-<?php echo str_replace(' ', '-',$row_rs_onsell['products_sku']); ?>/">
		
		
		
		
			<img src="<?php echo $objDynamicThumb1->Execute(); ?>" border="0" style="padding: 4px;"/>
		</a>
		
        
    </div>
    <div style="position: relative; display: table-cell; width: 191px; height: 100%;">
    	<div style="padding: 8px 8px 4px 8px; font-size: 14px;">
        	<?php echo $row_rs_onsell['manufacturers_title']; ?> <?php echo $row_rs_onsell['products_sku']; ?>
        </div>
        <div style="padding: 4px 8px 4px 8px; font-size: 12px;">
            <?php echo $row_rs_onsell['products_title']; ?>
        </div>
    	<div style="position: absolute; bottom: 5px; left: 8px;">
        	<!--<a href="#" class="buy_now_button" style="box-shadow: 0px 0px 1px 2px rgba(0,0,0,0.2); float: right; margin: 10px 10px 7px 7px;">BUY</a>-->
            <form action="" method="post" style="float: right; margin: 10px 10px 7px 3px;">
            <input type="hidden" name='quantity' value="1"> 
            <input type="hidden" name="session_id" value="<?php echo $PHPSESSID; ?>">
            <input name="product_id" type="hidden" value="<?php echo $row_rs_onsell['products_id']; ?>">
            <input type="hidden" name="price" value="<?php echo $row_rs_onsell['products_regularPrice']; ?>">
            <input type="submit" value="Buy" name="KT_Insert1" class="buy_now_button" style="box-shadow: 0px 0px 1px 2px rgba(0,0,0,0.2); color: white;" />
            <!--<a href="#" class="buy_now_button" style="box-shadow: 0px 0px 1px 2px rgba(0,0,0,0.2); color: white;">BUY</a>	-->
            </form>
        	
        	<?
			if($row_rs_onsell['subcategories_subcategorygroup_id']) {
				$setSubcategoryGroupsId=$row_rs_onsell['subcategories_subcategorygroup_id'];
			} else {
				$setSubcategoryGroupsId=0;
			}

			if($row_rs_onsell['subcategories_id']) {
				$setSubcategoriesId=$row_rs_onsell['subcategories_id'];
			} else {
				$setSubcategoriesId=0;
			}

			if($row_rs_onsell['subcategories_title']) {
				$setSubcategories_title=$row_rs_onsell['subcategories_title'];
			} else {
				$setSubcategories_title=0;
			}

		?>
			<a href="/product/<?php echo $row_rs_onsell['categories_id']; ?>/<?php echo $setSubcategoryGroupsId; ?>/<?php echo $setSubcategoriesId; ?>/<?php echo $row_rs_onsell['products_id']; ?>/<?php echo $setSubcategories_title; ?>/<?php echo str_replace(' ', '-',$row_rs_onsell['categories_title']); ?>/<?php echo str_replace(' ', '-',$row_rs_onsell['manufacturers_title']); ?>-<?php echo str_replace(' ', '-',$row_rs_onsell['products_sku']); ?>/" class="details_button" style="box-shadow: 0px 0px 1px 2px rgba(0,0,0,0.2); float: left; margin: 10px 7px 7px 3px;">DETAILS</a>
			
			
        	<!--<a href="/products/index.php?categories_id=<?php echo $row_rs_onsell['categories_id']; ?>&subcategories_id=<?php echo $row_rs_onsell['subcategories_id']; ?>&subcategorygroups_id=<?php echo $row_rs_onsell['subcategories_subcategorygroup_id']; ?>&product_id=<?php echo $row_rs_onsell['products_id']; ?>&category=<?php echo $row_rs_onsell['categories_title']; ?>&subcategory=<?php echo $row_rs_onsell['subcategories_title']; ?>&manufacturer=<?php echo $row_rs_onsell['manufacturers_title']; ?>&product=<?php echo $row_rs_onsell['products_sku']; ?>" class="details_button" style="box-shadow: 0px 0px 1px 2px rgba(0,0,0,0.2); float: left; margin: 10px 7px 7px 3px;">DETAILS</a>-->
    		
        </div>
    </div>
</div>

<?php
mysql_free_result($rs_onsell);
?>
